# Use an OpenJDK image
FROM openjdk:17-jdk-alpine

# Set the working directory
WORKDIR /app

# Copy the jar file generated by the Spring Boot application
COPY target/healthtrack-0.0.4-SNAPSHOT.jar /app.healthtrack-0.0.4-SNAPSHOT.jar

# Expose the port that the Spring Boot app will run on
EXPOSE 8080

# Command to run the jar filemvn 
ENTRYPOINT ["java", "-jar", "/app.healthtrack-0.0.4-SNAPSHOT.jar"]